### ISSUE TITLE
Page refresh after sending

### ISSUE THREAD

**Issue by cregx** [jan-vince/smallcontactform#83]
Since the update from version 1.25.0 I noticed a problem after sending the contact form.
My contact form can be found at the bottom of the footer of my website. To see and use this, the user has to scroll down to the bottom.
After sending the contact form (xhr) the website is refreshed and the user has to scroll down to see the success message.

**Comment by jan-vince** [comment]
Hi @cregx and thanks for this - I have fixed it in a new version (ready on GitHub and asap on Marketplace).

**Comment by djrallard** [comment]
> Hi @cregx and thanks for this - I have fixed it in a new version (ready on GitHub and asap on Marketplace).

I have version 1.32.1 install from OctoberCMS plugins page and I’m still seeing the page refresh issue after submitting the form. Can you please confirm this is fixed and in what version it was fixed?

**Comment by jan-vince** [comment]
Hi @djrallard, Small Contact form supports both sending methods - default is standard POST, optionally you can allow AJAX send.

When default POST mode is active, the page must be refreshed.

When AJAX is active, no refresh is needed (I can confirm, this works for me).
